### ISSUE TITLE
Logging does not work

### ISSUE THREAD

**Issue by johadalin** [Metaswitch/libnss-ato#5]
Attempts were made to log out the name of the process calling into the ato component, as well as to add logs for the main processing steps in the function. 
It was hoped that these would output to /var/log/auth.log, using syslog, but they do not seem to be appearing. 
Some more investigation should be done to find out why, and alter the log entries appropriately so that they output useful information. 
The log outputs can then be used to determine which process to white list for given operations.

**Comment by eleanor-merry** [comment]
I'm seeing these logs come through, so closing this issue
